### ISSUE TITLE
Could you please provide .rmd or r file of tutorial as well. 

### ISSUE THREAD

**Issue by amarinderthind** [bhattacharya-a-bt/NanoNormIter#1]
Hi Arjun,

Could you please provide a .rmd or .r file of the tutorial as well? It can help the user to execute the pipeline fast. 
Where can I find the nanostring_functions.R file? do this include readRcc function? or readRCC is just like reading a normal file.

**Comment by mdidish** [comment]
You should look at [sabry_analysis.R](https://github.com/bhattacharya-a-bt/CBCS_normalization/blob/master/sabry_analysis.R) to see a real analysis.

- nanostring_functions.R : install NanoNormIter `devtools::install_github('bhattacharya-a-bt/NanoNormIter')` to import `RUV_total()`.
- readRCC fuction : NanoStringQCPro package (`#BiocManager::install("NanoStringQCPro")`)
