### ISSUE TITLE
Normalised data usage

### ISSUE THREAD

**Issue by faraz89** [bhattacharya-a-bt/NanoNormIter#2]
Hi,

Can the normalised data processed by RUVseq be imported into nSolver Advanced Analysis suite for further downstream analysis? 

Faraz

**Comment by bhattacharya-a-bt** [comment]
I'm not quite sure about this - I don't use the nSolver suite for
downstream analyses. I'm pretty sure that the transcriptomic analyses
you'll want to run on RUVseq-normalized expression data can be conducted in
R.
----
Arjun Bhattacharya, PhD
Postdoctoral Fellow
Department of Pathology and Laboratory Medicine
Computational Medicine
Institute for Quantitative and Computational Biosciences
David Geffen School of Medicine
University of California, Los Angeles

**Comment by faraz89** [comment]
Thanks. Just out of curiosity. What R package(es) you use for downstream analysis (DE,GSA,Fusion,SNV)?

best,
F

**Comment by bhattacharya-a-bt** [comment]
I would use either limma or DESeq2 for differential expression,
clusterProfiler for GSA. I'm not sure what you mean by Fusion or SNV? Are
you trying to call variants from Nanostring data?

**Comment by faraz89** [comment]
Right. So you are using the same packages that are used for NGS RNA-seq data. Fair enough. Thanks. 

Yes I meant SNV analysis for nanostring data.

**Comment by bhattacharya-a-bt** [comment]
Again - not totally sure what you mean by SNV analysis for Nanostring data:
Do you mean eQTL analysis or calling genotypes from Nanostring data? The
latter is not possible since you don't have a sequence.

**Comment by faraz89** [comment]
<img width="699" alt="Screenshot 2022-06-30 at 18 03 43" src="https://user-images.githubusercontent.com/24622959/176786595-f3ca6899-4c31-4081-afb6-6ed966f8cb5b.png">

Please see attached screenshot for the type of analysis I was talking about.

**Comment by bhattacharya-a-bt** [comment]
I'm not familiar with this unfortunately - I've only dealt with the RNA
expression data from NanoString.
